### ISSUE TITLE
When the paper is going to be released?

### ISSUE THREAD

**Issue by liuh886** [rhugonnet/dem_error_study#2]
Hi, I am a master's student working on DEM uncertainty and ICESat-2. I am looking forward to your paper, Hugonnet et al. (2022), Uncertainty analysis of digital elevation models by spatial inference from stable terrain. Is it possible to read it online? 

This may not be a proper issue, I can delete it if needed.

My email is _zhihaol@uio.no_

**Comment by rhugonnet** [comment]
Hi @liuh886!
The paper will likely still take a few weeks (possibly months) to be published. I'll send you the latest version by email.

**Comment by rhugonnet** [comment]
For the record on this issue, the paper is now available on early access here: https://doi.org/10.1109/JSTARS.2022.3188922.
